# Generated by Django 5.0.7 on 2025-04-16 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentstore',
            name='competition',
            field=models.CharField(choices=[('SCHOOL', 'School'), ('CUET', 'CUET'), ('JEE_MAINS', 'JEE Mains'), ('JEE_ADVANCE', 'JEE Advance'), ('NEET', 'NEET'), ('NDA', 'NDA'), ('CLAT', 'CLAT'), ('OLYMPIAD', 'Olympiad')], default='SCHOOL', max_length=255),
        ),
    ]
